# GIT BASIC COMMANDS = ES IMPORTANTE ESCRIBIR TODOOOO EXACTAMENTE IGUAL -CASE SENSITIVE-

# GIT PULL

# GIT INIT = Se usa para iniciar un prouecto en X carpeta - 
# Luego de iniciarlo se crea una carpeta donde se llevaran los registros del codigo, pero no se debe modificar nunca

# GIT ADD <FILE>

# GIT COMMIT

# GIT PUSH

# GIT PULL

# GIT CLONE

# GIT STATUS = Para ver el estado de nuestros archivos

# GIT DIFF = Para ver los cambios efectuados en los archivos

